

spring:
  config:
    import: optional:file:.env[.properties]

  profiles:
      active: ${SPRING_PROFILES_ACTIVE:default}
  application:
    name: demo
  security:
    oauth2:
        resourceserver:
          jwt:
            issuer-uri: ${KEYCLOAK_URL}
    user:
      name: admin
      password: admin

server:
  servlet:
    context-path: /api

