spring:
  config:
    import: optional:file:.env[.properties]

  profiles:
      active: ${SPRING_PROFILES_ACTIVE:default}
  application:
    name: demo
  security:
    oauth2:
        resourceserver:
          jwt:
            issuer-uri: ${KEYCLOAK_URL}
    user:
      name: admin
      password: admin
    redis:
        host: ${REDIS_HOST:localhost}
        port: ${REDIS_PORT:6379}

server:
  address: ${APP_SERVER_ADD:0.0.0.0}
  servlet:
    context-path: /api

